// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: remote_interface_info.proto
package com.bigflag.toolkit.rpc.beans;
public final class RemoteInterfaceInfoProtobuf {
  private RemoteInterfaceInfoProtobuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string interfaceFullName = 1;</code>
     */
    boolean hasInterfaceFullName();
    /**
     * <code>required string interfaceFullName = 1;</code>
     */
    java.lang.String getInterfaceFullName();
    /**
     * <code>required string interfaceFullName = 1;</code>
     */
    com.google.protobuf.ByteString
        getInterfaceFullNameBytes();

    /**
     * <code>required int32 version = 3;</code>
     */
    boolean hasVersion();
    /**
     * <code>required int32 version = 3;</code>
     */
    int getVersion();

    /**
     * <code>required string serviceURI = 4;</code>
     */
    boolean hasServiceURI();
    /**
     * <code>required string serviceURI = 4;</code>
     */
    java.lang.String getServiceURI();
    /**
     * <code>required string serviceURI = 4;</code>
     */
    com.google.protobuf.ByteString
        getServiceURIBytes();

    /**
     * <code>required string interfaceType = 5;</code>
     */
    boolean hasInterfaceType();
    /**
     * <code>required string interfaceType = 5;</code>
     */
    java.lang.String getInterfaceType();
    /**
     * <code>required string interfaceType = 5;</code>
     */
    com.google.protobuf.ByteString
        getInterfaceTypeBytes();

    /**
     * <code>required int32 healthStatus = 6;</code>
     */
    boolean hasHealthStatus();
    /**
     * <code>required int32 healthStatus = 6;</code>
     */
    int getHealthStatus();

    /**
     * <code>required int32 invokeWeight = 7;</code>
     */
    boolean hasInvokeWeight();
    /**
     * <code>required int32 invokeWeight = 7;</code>
     */
    int getInvokeWeight();

    /**
     * <code>required string serviceProvider = 8;</code>
     */
    boolean hasServiceProvider();
    /**
     * <code>required string serviceProvider = 8;</code>
     */
    java.lang.String getServiceProvider();
    /**
     * <code>required string serviceProvider = 8;</code>
     */
    com.google.protobuf.ByteString
        getServiceProviderBytes();

    /**
     * <code>required string invokeType = 9;</code>
     */
    boolean hasInvokeType();
    /**
     * <code>required string invokeType = 9;</code>
     */
    java.lang.String getInvokeType();
    /**
     * <code>required string invokeType = 9;</code>
     */
    com.google.protobuf.ByteString
        getInvokeTypeBytes();
  }
  /**
   * Protobuf type {@code Message}
   */
  public  static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      interfaceFullName_ = "";
      version_ = 0;
      serviceURI_ = "";
      interfaceType_ = "";
      healthStatus_ = 0;
      invokeWeight_ = 0;
      serviceProvider_ = "";
      invokeType_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              interfaceFullName_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000002;
              version_ = input.readInt32();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              serviceURI_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              interfaceType_ = bs;
              break;
            }
            case 48: {
              bitField0_ |= 0x00000010;
              healthStatus_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000020;
              invokeWeight_ = input.readInt32();
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              serviceProvider_ = bs;
              break;
            }
            case 74: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000080;
              invokeType_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RemoteInterfaceInfoProtobuf.internal_static_Message_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RemoteInterfaceInfoProtobuf.internal_static_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RemoteInterfaceInfoProtobuf.Message.class, RemoteInterfaceInfoProtobuf.Message.Builder.class);
    }

    private int bitField0_;
    public static final int INTERFACEFULLNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object interfaceFullName_;
    /**
     * <code>required string interfaceFullName = 1;</code>
     */
    public boolean hasInterfaceFullName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string interfaceFullName = 1;</code>
     */
    public java.lang.String getInterfaceFullName() {
      java.lang.Object ref = interfaceFullName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          interfaceFullName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string interfaceFullName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getInterfaceFullNameBytes() {
      java.lang.Object ref = interfaceFullName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        interfaceFullName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VERSION_FIELD_NUMBER = 3;
    private int version_;
    /**
     * <code>required int32 version = 3;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 version = 3;</code>
     */
    public int getVersion() {
      return version_;
    }

    public static final int SERVICEURI_FIELD_NUMBER = 4;
    private volatile java.lang.Object serviceURI_;
    /**
     * <code>required string serviceURI = 4;</code>
     */
    public boolean hasServiceURI() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string serviceURI = 4;</code>
     */
    public java.lang.String getServiceURI() {
      java.lang.Object ref = serviceURI_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          serviceURI_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string serviceURI = 4;</code>
     */
    public com.google.protobuf.ByteString
        getServiceURIBytes() {
      java.lang.Object ref = serviceURI_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serviceURI_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INTERFACETYPE_FIELD_NUMBER = 5;
    private volatile java.lang.Object interfaceType_;
    /**
     * <code>required string interfaceType = 5;</code>
     */
    public boolean hasInterfaceType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string interfaceType = 5;</code>
     */
    public java.lang.String getInterfaceType() {
      java.lang.Object ref = interfaceType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          interfaceType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string interfaceType = 5;</code>
     */
    public com.google.protobuf.ByteString
        getInterfaceTypeBytes() {
      java.lang.Object ref = interfaceType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        interfaceType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HEALTHSTATUS_FIELD_NUMBER = 6;
    private int healthStatus_;
    /**
     * <code>required int32 healthStatus = 6;</code>
     */
    public boolean hasHealthStatus() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 healthStatus = 6;</code>
     */
    public int getHealthStatus() {
      return healthStatus_;
    }

    public static final int INVOKEWEIGHT_FIELD_NUMBER = 7;
    private int invokeWeight_;
    /**
     * <code>required int32 invokeWeight = 7;</code>
     */
    public boolean hasInvokeWeight() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required int32 invokeWeight = 7;</code>
     */
    public int getInvokeWeight() {
      return invokeWeight_;
    }

    public static final int SERVICEPROVIDER_FIELD_NUMBER = 8;
    private volatile java.lang.Object serviceProvider_;
    /**
     * <code>required string serviceProvider = 8;</code>
     */
    public boolean hasServiceProvider() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required string serviceProvider = 8;</code>
     */
    public java.lang.String getServiceProvider() {
      java.lang.Object ref = serviceProvider_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          serviceProvider_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string serviceProvider = 8;</code>
     */
    public com.google.protobuf.ByteString
        getServiceProviderBytes() {
      java.lang.Object ref = serviceProvider_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serviceProvider_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INVOKETYPE_FIELD_NUMBER = 9;
    private volatile java.lang.Object invokeType_;
    /**
     * <code>required string invokeType = 9;</code>
     */
    public boolean hasInvokeType() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required string invokeType = 9;</code>
     */
    public java.lang.String getInvokeType() {
      java.lang.Object ref = invokeType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          invokeType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string invokeType = 9;</code>
     */
    public com.google.protobuf.ByteString
        getInvokeTypeBytes() {
      java.lang.Object ref = invokeType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        invokeType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasInterfaceFullName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasServiceURI()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasInterfaceType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHealthStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasInvokeWeight()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasServiceProvider()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasInvokeType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, interfaceFullName_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(3, version_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, serviceURI_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, interfaceType_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(6, healthStatus_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(7, invokeWeight_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, serviceProvider_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, invokeType_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, interfaceFullName_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, version_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, serviceURI_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, interfaceType_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, healthStatus_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, invokeWeight_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, serviceProvider_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, invokeType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof RemoteInterfaceInfoProtobuf.Message)) {
        return super.equals(obj);
      }
      RemoteInterfaceInfoProtobuf.Message other = (RemoteInterfaceInfoProtobuf.Message) obj;

      boolean result = true;
      result = result && (hasInterfaceFullName() == other.hasInterfaceFullName());
      if (hasInterfaceFullName()) {
        result = result && getInterfaceFullName()
            .equals(other.getInterfaceFullName());
      }
      result = result && (hasVersion() == other.hasVersion());
      if (hasVersion()) {
        result = result && (getVersion()
            == other.getVersion());
      }
      result = result && (hasServiceURI() == other.hasServiceURI());
      if (hasServiceURI()) {
        result = result && getServiceURI()
            .equals(other.getServiceURI());
      }
      result = result && (hasInterfaceType() == other.hasInterfaceType());
      if (hasInterfaceType()) {
        result = result && getInterfaceType()
            .equals(other.getInterfaceType());
      }
      result = result && (hasHealthStatus() == other.hasHealthStatus());
      if (hasHealthStatus()) {
        result = result && (getHealthStatus()
            == other.getHealthStatus());
      }
      result = result && (hasInvokeWeight() == other.hasInvokeWeight());
      if (hasInvokeWeight()) {
        result = result && (getInvokeWeight()
            == other.getInvokeWeight());
      }
      result = result && (hasServiceProvider() == other.hasServiceProvider());
      if (hasServiceProvider()) {
        result = result && getServiceProvider()
            .equals(other.getServiceProvider());
      }
      result = result && (hasInvokeType() == other.hasInvokeType());
      if (hasInvokeType()) {
        result = result && getInvokeType()
            .equals(other.getInvokeType());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasInterfaceFullName()) {
        hash = (37 * hash) + INTERFACEFULLNAME_FIELD_NUMBER;
        hash = (53 * hash) + getInterfaceFullName().hashCode();
      }
      if (hasVersion()) {
        hash = (37 * hash) + VERSION_FIELD_NUMBER;
        hash = (53 * hash) + getVersion();
      }
      if (hasServiceURI()) {
        hash = (37 * hash) + SERVICEURI_FIELD_NUMBER;
        hash = (53 * hash) + getServiceURI().hashCode();
      }
      if (hasInterfaceType()) {
        hash = (37 * hash) + INTERFACETYPE_FIELD_NUMBER;
        hash = (53 * hash) + getInterfaceType().hashCode();
      }
      if (hasHealthStatus()) {
        hash = (37 * hash) + HEALTHSTATUS_FIELD_NUMBER;
        hash = (53 * hash) + getHealthStatus();
      }
      if (hasInvokeWeight()) {
        hash = (37 * hash) + INVOKEWEIGHT_FIELD_NUMBER;
        hash = (53 * hash) + getInvokeWeight();
      }
      if (hasServiceProvider()) {
        hash = (37 * hash) + SERVICEPROVIDER_FIELD_NUMBER;
        hash = (53 * hash) + getServiceProvider().hashCode();
      }
      if (hasInvokeType()) {
        hash = (37 * hash) + INVOKETYPE_FIELD_NUMBER;
        hash = (53 * hash) + getInvokeType().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static RemoteInterfaceInfoProtobuf.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RemoteInterfaceInfoProtobuf.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RemoteInterfaceInfoProtobuf.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RemoteInterfaceInfoProtobuf.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RemoteInterfaceInfoProtobuf.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RemoteInterfaceInfoProtobuf.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RemoteInterfaceInfoProtobuf.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RemoteInterfaceInfoProtobuf.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static RemoteInterfaceInfoProtobuf.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static RemoteInterfaceInfoProtobuf.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static RemoteInterfaceInfoProtobuf.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RemoteInterfaceInfoProtobuf.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(RemoteInterfaceInfoProtobuf.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Message)
        RemoteInterfaceInfoProtobuf.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RemoteInterfaceInfoProtobuf.internal_static_Message_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RemoteInterfaceInfoProtobuf.internal_static_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RemoteInterfaceInfoProtobuf.Message.class, RemoteInterfaceInfoProtobuf.Message.Builder.class);
      }

      // Construct using RemoteInterfaceInfoProtobuf.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        interfaceFullName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        serviceURI_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        interfaceType_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        healthStatus_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        invokeWeight_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        serviceProvider_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        invokeType_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RemoteInterfaceInfoProtobuf.internal_static_Message_descriptor;
      }

      public RemoteInterfaceInfoProtobuf.Message getDefaultInstanceForType() {
        return RemoteInterfaceInfoProtobuf.Message.getDefaultInstance();
      }

      public RemoteInterfaceInfoProtobuf.Message build() {
        RemoteInterfaceInfoProtobuf.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public RemoteInterfaceInfoProtobuf.Message buildPartial() {
        RemoteInterfaceInfoProtobuf.Message result = new RemoteInterfaceInfoProtobuf.Message(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.interfaceFullName_ = interfaceFullName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.serviceURI_ = serviceURI_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.interfaceType_ = interfaceType_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.healthStatus_ = healthStatus_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.invokeWeight_ = invokeWeight_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.serviceProvider_ = serviceProvider_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.invokeType_ = invokeType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RemoteInterfaceInfoProtobuf.Message) {
          return mergeFrom((RemoteInterfaceInfoProtobuf.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RemoteInterfaceInfoProtobuf.Message other) {
        if (other == RemoteInterfaceInfoProtobuf.Message.getDefaultInstance()) return this;
        if (other.hasInterfaceFullName()) {
          bitField0_ |= 0x00000001;
          interfaceFullName_ = other.interfaceFullName_;
          onChanged();
        }
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasServiceURI()) {
          bitField0_ |= 0x00000004;
          serviceURI_ = other.serviceURI_;
          onChanged();
        }
        if (other.hasInterfaceType()) {
          bitField0_ |= 0x00000008;
          interfaceType_ = other.interfaceType_;
          onChanged();
        }
        if (other.hasHealthStatus()) {
          setHealthStatus(other.getHealthStatus());
        }
        if (other.hasInvokeWeight()) {
          setInvokeWeight(other.getInvokeWeight());
        }
        if (other.hasServiceProvider()) {
          bitField0_ |= 0x00000040;
          serviceProvider_ = other.serviceProvider_;
          onChanged();
        }
        if (other.hasInvokeType()) {
          bitField0_ |= 0x00000080;
          invokeType_ = other.invokeType_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasInterfaceFullName()) {
          return false;
        }
        if (!hasVersion()) {
          return false;
        }
        if (!hasServiceURI()) {
          return false;
        }
        if (!hasInterfaceType()) {
          return false;
        }
        if (!hasHealthStatus()) {
          return false;
        }
        if (!hasInvokeWeight()) {
          return false;
        }
        if (!hasServiceProvider()) {
          return false;
        }
        if (!hasInvokeType()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        RemoteInterfaceInfoProtobuf.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (RemoteInterfaceInfoProtobuf.Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object interfaceFullName_ = "";
      /**
       * <code>required string interfaceFullName = 1;</code>
       */
      public boolean hasInterfaceFullName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string interfaceFullName = 1;</code>
       */
      public java.lang.String getInterfaceFullName() {
        java.lang.Object ref = interfaceFullName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            interfaceFullName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string interfaceFullName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getInterfaceFullNameBytes() {
        java.lang.Object ref = interfaceFullName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          interfaceFullName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string interfaceFullName = 1;</code>
       */
      public Builder setInterfaceFullName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        interfaceFullName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string interfaceFullName = 1;</code>
       */
      public Builder clearInterfaceFullName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        interfaceFullName_ = getDefaultInstance().getInterfaceFullName();
        onChanged();
        return this;
      }
      /**
       * <code>required string interfaceFullName = 1;</code>
       */
      public Builder setInterfaceFullNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        interfaceFullName_ = value;
        onChanged();
        return this;
      }

      private int version_ ;
      /**
       * <code>required int32 version = 3;</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 version = 3;</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <code>required int32 version = 3;</code>
       */
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000002;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 version = 3;</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000002);
        version_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object serviceURI_ = "";
      /**
       * <code>required string serviceURI = 4;</code>
       */
      public boolean hasServiceURI() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string serviceURI = 4;</code>
       */
      public java.lang.String getServiceURI() {
        java.lang.Object ref = serviceURI_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            serviceURI_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string serviceURI = 4;</code>
       */
      public com.google.protobuf.ByteString
          getServiceURIBytes() {
        java.lang.Object ref = serviceURI_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serviceURI_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string serviceURI = 4;</code>
       */
      public Builder setServiceURI(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        serviceURI_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string serviceURI = 4;</code>
       */
      public Builder clearServiceURI() {
        bitField0_ = (bitField0_ & ~0x00000004);
        serviceURI_ = getDefaultInstance().getServiceURI();
        onChanged();
        return this;
      }
      /**
       * <code>required string serviceURI = 4;</code>
       */
      public Builder setServiceURIBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        serviceURI_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object interfaceType_ = "";
      /**
       * <code>required string interfaceType = 5;</code>
       */
      public boolean hasInterfaceType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string interfaceType = 5;</code>
       */
      public java.lang.String getInterfaceType() {
        java.lang.Object ref = interfaceType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            interfaceType_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string interfaceType = 5;</code>
       */
      public com.google.protobuf.ByteString
          getInterfaceTypeBytes() {
        java.lang.Object ref = interfaceType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          interfaceType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string interfaceType = 5;</code>
       */
      public Builder setInterfaceType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        interfaceType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string interfaceType = 5;</code>
       */
      public Builder clearInterfaceType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        interfaceType_ = getDefaultInstance().getInterfaceType();
        onChanged();
        return this;
      }
      /**
       * <code>required string interfaceType = 5;</code>
       */
      public Builder setInterfaceTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        interfaceType_ = value;
        onChanged();
        return this;
      }

      private int healthStatus_ ;
      /**
       * <code>required int32 healthStatus = 6;</code>
       */
      public boolean hasHealthStatus() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 healthStatus = 6;</code>
       */
      public int getHealthStatus() {
        return healthStatus_;
      }
      /**
       * <code>required int32 healthStatus = 6;</code>
       */
      public Builder setHealthStatus(int value) {
        bitField0_ |= 0x00000010;
        healthStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 healthStatus = 6;</code>
       */
      public Builder clearHealthStatus() {
        bitField0_ = (bitField0_ & ~0x00000010);
        healthStatus_ = 0;
        onChanged();
        return this;
      }

      private int invokeWeight_ ;
      /**
       * <code>required int32 invokeWeight = 7;</code>
       */
      public boolean hasInvokeWeight() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required int32 invokeWeight = 7;</code>
       */
      public int getInvokeWeight() {
        return invokeWeight_;
      }
      /**
       * <code>required int32 invokeWeight = 7;</code>
       */
      public Builder setInvokeWeight(int value) {
        bitField0_ |= 0x00000020;
        invokeWeight_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 invokeWeight = 7;</code>
       */
      public Builder clearInvokeWeight() {
        bitField0_ = (bitField0_ & ~0x00000020);
        invokeWeight_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object serviceProvider_ = "";
      /**
       * <code>required string serviceProvider = 8;</code>
       */
      public boolean hasServiceProvider() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required string serviceProvider = 8;</code>
       */
      public java.lang.String getServiceProvider() {
        java.lang.Object ref = serviceProvider_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            serviceProvider_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string serviceProvider = 8;</code>
       */
      public com.google.protobuf.ByteString
          getServiceProviderBytes() {
        java.lang.Object ref = serviceProvider_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serviceProvider_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string serviceProvider = 8;</code>
       */
      public Builder setServiceProvider(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        serviceProvider_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string serviceProvider = 8;</code>
       */
      public Builder clearServiceProvider() {
        bitField0_ = (bitField0_ & ~0x00000040);
        serviceProvider_ = getDefaultInstance().getServiceProvider();
        onChanged();
        return this;
      }
      /**
       * <code>required string serviceProvider = 8;</code>
       */
      public Builder setServiceProviderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        serviceProvider_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object invokeType_ = "";
      /**
       * <code>required string invokeType = 9;</code>
       */
      public boolean hasInvokeType() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required string invokeType = 9;</code>
       */
      public java.lang.String getInvokeType() {
        java.lang.Object ref = invokeType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            invokeType_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string invokeType = 9;</code>
       */
      public com.google.protobuf.ByteString
          getInvokeTypeBytes() {
        java.lang.Object ref = invokeType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          invokeType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string invokeType = 9;</code>
       */
      public Builder setInvokeType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        invokeType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string invokeType = 9;</code>
       */
      public Builder clearInvokeType() {
        bitField0_ = (bitField0_ & ~0x00000080);
        invokeType_ = getDefaultInstance().getInvokeType();
        onChanged();
        return this;
      }
      /**
       * <code>required string invokeType = 9;</code>
       */
      public Builder setInvokeTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        invokeType_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Message)
    }

    // @@protoc_insertion_point(class_scope:Message)
    private static final RemoteInterfaceInfoProtobuf.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new RemoteInterfaceInfoProtobuf.Message();
    }

    public static RemoteInterfaceInfoProtobuf.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    public RemoteInterfaceInfoProtobuf.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033remote_interface_info.proto\"\271\001\n\007Messag" +
      "e\022\031\n\021interfaceFullName\030\001 \002(\t\022\017\n\007version\030" +
      "\003 \002(\005\022\022\n\nserviceURI\030\004 \002(\t\022\025\n\rinterfaceTy" +
      "pe\030\005 \002(\t\022\024\n\014healthStatus\030\006 \002(\005\022\024\n\014invoke" +
      "Weight\030\007 \002(\005\022\027\n\017serviceProvider\030\010 \002(\t\022\022\n" +
      "\ninvokeType\030\t \002(\tB\035B\033RemoteInterfaceInfo" +
      "Protobuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_descriptor,
        new java.lang.String[] { "InterfaceFullName", "Version", "ServiceURI", "InterfaceType", "HealthStatus", "InvokeWeight", "ServiceProvider", "InvokeType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
